spring:
  application:
    name: cardmore
  jackson:
    time-zone: Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  data:
    elasticsearch:
      repositories:
        enabled: true
      url: ${ELASTICSEARCH_URL}:${ELASTICSEARCH_PORT}
    redis:
      password: ${REDIS_PASSWORD}
      cluster:
        nodes: ${REDIS_NODES}
        max-redirects: 6

jwt:
  secret-key: ${SECRET_KEY}
  access-token-exp: ${ACCESS_TOKEN_EXP}
  refresh-token-exp: ${REFRESH_TOKEN_EXP}

fintech:
  api:
    url: ${FINTECH_API_URL}
    key: ${FINTECH_API_KEY}
  app:
    no: ${FINTECH_API_NO}
  institution:
    code: ${FINTECH_INSTITUTION_CODE}

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  api-docs:
    enabled: true
    path: '/docs'
  swagger-ui:
    enabled: true
    path: '/swagger'
    try-it-out-enabled: true
    operations-sorter: alpha

logging:
  level:
    a107.cardmore: debug
